### PR TITLE
Add code to rebuild pmedian table

### PR DESCRIPTION
**Pull request by odow**
Code for the nicely formatted Latex table in the paper:

image

Skips cvxpy which we can input separately.

### CODE REVIEW

**Comment by joaquimg** [comment]
The main caveat here is that solve isn't exactly solve. Its like run 1 ms.

**Comment by odow** [comment]
True. I should switch to one simplex iteration? It doesn't really matter, so long as we are consistent.

**Comment by odow** [comment]
Although you can't even see 1 ms of time in that table.

**Comment by joaquimg** [comment]
I think we could add both limits `it_lim = 1` and `tm_lim = 1`.
This way we get the minimum.
And yes, the most important is to be consistent, and we are.
The other thing is adding this comment in text.

**Comment by odow** [comment]
Merging so I can run everything off the same commit.

**Pull request merged**
